services:
  app:
    container_name: techin8-profile-scraper
    volumes:
      - ./:/code
      - /code/.venv

  database:
    container_name: techin8-rofile-scraper
    ports:
      - ${POSTGRES_PORT:-3201}:5432
